### ISSUE TITLE
ENOENT when execa call "deno -v" on OSX

### ISSUE THREAD

**Issue by bios21** [justjavac/vscode-deno#20]
**Describe the bug**
After installing Deno and "vscode-deno", the extension is simply not working.

After debugging the extension I've found this error:  
`Error: spawn deno ENOENT`

**To Reproduce**
1. Install deno
2. Install vscode
3. Install extension

**Expected behavior**
The extension should detect deno and start.

**Screenshots**

On `utils.ts` (generated js edited to output error):
![image](https://user-images.githubusercontent.com/5783789/56071682-1c1f5500-5d90-11e9-9fba-8de83e020837.png)

### Versions

extension: 1.0.7
deno -v
```
deno: 0.3.7
v8: 7.4.238
typescript: 3.4.1
```
code -v
```
1.33.1
51b0b28134d51361cf996d2f0a1c698247aeabd8
x64
```
OSX Mojave 10.14.4

**Comment by euphbriggs** [comment]
I ran into this issue as well. I have `deno` in my user's PATH, but not the system's PATH. Adding a symlink to the system's PATH (and restarting VS Code) resolved the issue for me.

I'm on running on Linux, so I put a symlink in `/usr/bin/deno` but I image it'd be similar on macOS.
