### ISSUE TITLE
.tsx file support

### ISSUE THREAD

**Issue by Banou26** [justjavac/vscode-deno#27]
**Is your feature request related to a problem? Please describe.**

Your extension is only active in .ts files, not including his variants (.tsx).

**Describe the solution you'd like**

Enabling all the features this extension gives in .tsx files.

**Additional context**

I love this extension because it fixed one of my problems with typescript
`ts(2691): An import path cannot end with a '.ts' extension. Consider importing './foo' instead.`
And right now i have to use React so JSX is needed, but since i'm in a .tsx file, all the good features your extension provide aren't enabled.

**Comment by axetroy** [comment]
This should be done by `typescript-deno-plugin`. port to #21
