### ISSUE TITLE
compilerOptions strict true does not work anymore with extension enabled

### ISSUE THREAD

**Issue by lastmjs** [justjavac/vscode-deno#34]
**Describe the bug**

I have `"strict": true` set in my `"compilerOptions"` in my `tsconfig.json`. I just enabled the deno extension today, and everything seemed to be working rather well. But, I noticed I stopped getting TypeScript errors in my editor for null checks and implicit anys. I restarted VS Code and nothing changed. I disabled the deno extension and restarted VS Code, and the strict checking came back. Bummer.

**To Reproduce**

1. Create a TypeScript project with a tsconfig.json file, and set strict to true
2. Create a function with an implicit any, or try to access a property on an object that can possibly be null

**Expected behavior**

VS Code should show red squiggles. It doesn't.

### Versions

Code version (I am using Code, not VS Code): I don't know

**Comment by lastmjs** [comment]
Wait, is the plugin overriding my local tsconfig.json file? If so, that's undesirable and confusing

**Comment by justjavac** [comment]
The typescript-deno-plugin provides a [default configuration](https://github.com/justjavac/typescript-deno-plugin/blob/cac55f5e9f3af47c5f172d79872ee886016f373d/src/index.ts#L18-L31), that will [merge the project configuration into the default configuration](https://github.com/justjavac/typescript-deno-plugin/blob/cac55f5e9f3af47c5f172d79872ee886016f373d/src/index.ts#L65-L68) when the plugin is running. local tsconfig.json will overrides the plugin's.

**Comment by axetroy** [comment]
@justjavac However, this is not a deep merger.

I got the same problem
