### ISSUE TITLE
cause can't find fs of node module!

### ISSUE THREAD

**Issue by Akimotorakiyu** [justjavac/vscode-deno#36]
**Describe the bug**

if I use this plugin, when I write ts-node project, it cause can't find fs of node module even I installed @types/node。

**To Reproduce**

1. [First Step]
```bash
yarn init -y
yarn add typescript ts-node
yarn add @types/node
```
2. [Second Step]
make index.ts
```ts
import fs = require( "fs")
```
3. [and so on...]

**Expected behavior**

no warning

**Screenshots**

![图片](https://user-images.githubusercontent.com/31165554/58933420-c072b600-8799-11e9-97d3-3cc14272985b.png)

### Versions

You can get this information from copy and pasting the output of `deno --version` from the command line. Also, please include the VS Code's versions.

**Additional context**

**Comment by justjavac** [comment]
Now this extension only supports pure deno projects, but I haven't figured out how to distinguish whether a project is a deno project.

**Comment by SilverLeaves** [comment]
a `package.json` file, isn't it?

**Comment by justjavac** [comment]
close via https://github.com/denoland/vscode_deno/pull/7
