### ISSUE TITLE
Support for import maps

### ISSUE THREAD

**Issue by NathanSMB** [justjavac/vscode-deno#41]
**Is your feature request related to a problem? Please describe.**

Currently if you import a module from an import map then ts(2691) is emitted.

**Describe the solution you'd like**

The ts(2691) error should be suppressed when importing from an import map the same way it is for other imports.

**Additional context**

Deno recently added support for import maps. See [#2360](https://github.com/denoland/deno/pull/2360)

In the example below you can see deno runs the code just fine but an error is still shown.

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/15826580/59575398-66bb9700-9089-11e9-8125-d2ae2bf5f795.png">

Also the [import maps specification](https://github.com/WICG/import-maps) should be useful.

**Comment by justjavac** [comment]
supported
