### ISSUE TITLE
Install vscode-deno will destroy the display of normal node TS project

### ISSUE THREAD

**Issue by mapleeit** [justjavac/vscode-deno#47]
**Describe the bug**

Vscode-deno plugin will destroy normal import of NodeJS project.

**To Reproduce**

1. `git clone https://github.com/mapleeit/reproduce-vscode-deno-bug.git`
2. `yarn install`
3. Open this project with vscode.
4. Open `index.ts` file.

When not install vscode-deno, everything is fine.

![image](https://user-images.githubusercontent.com/4194287/61791789-8c3c7d00-ae4d-11e9-8381-f32f09242027.png)

**When installed:**

![image](https://user-images.githubusercontent.com/4194287/61791820-9cecf300-ae4d-11e9-9f25-1e3a5e439678.png)

**Expected behavior**

Don't throw Error.

**Screenshots**

See above.

### Versions

Version: 1.37.0-insider
Commit: 188180bccf1f56b3368c4eb20e877238d69925b8
Date: 2019-07-24T05:33:34.928Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

deno: 0.12.0
v8: 7.7.200
typescript: 3.5.1

**Comment by justjavac** [comment]
same as https://github.com/justjavac/vscode-deno/issues/44

**Comment by mapleeit** [comment]
Close this because of duplication.
