### ISSUE TITLE
Suppress import.meta error

### ISSUE THREAD

**Issue by dev-nicolaos** [justjavac/vscode-deno#48]
**Describe the bug**

When developing for Deno, use of `import.meta` results in vs-code throwing ts(1343)

**To Reproduce**

1. Open a new JS or TS file in VS Code
1. Ensure the Deno extension is enabled and running
1. Type `console.log(import.meta.url);`
1, Observe that `import.meta` is underlined with an error and ts(1343) shows in problems panel

**Expected behavior**

Deno supports use of `import.meta` so I would expect the extension to suppress this error.

**Screenshots**

![image](https://user-images.githubusercontent.com/29005473/63075389-5dfb0c00-bee6-11e9-9b88-ac058ec8cbdf.png)

### Versions
VS Code: 1.37
Deno: 0.15.0
VS Code Deno Extension: 1.3.2

**Comment by axetroy** [comment]
workaround

create file `tsconfig.json` in your workspace

```json
{
  "compilerOptions": {
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

**Comment by axetroy** [comment]
This have been resolve in a new extension https://github.com/axetroy/vscode-deno

![截屏2020-01-2500 37 22](https://user-images.githubusercontent.com/9758711/73086084-e1477180-3f0a-11ea-841b-d809bfeecf82.png)

**Comment by justjavac** [comment]
already supported
