### ISSUE TITLE
Wrong formatting

### ISSUE THREAD

**Issue by timreichen** [justjavac/vscode-deno#54]
**Describe the bug**
If code is formatted with this extension enabled, it will always add semicolons to end of lines, even if it is disabled by the code formatter in vscode.

**To Reproduce**

1. install deno extension
2. open ts file
3. press shift-alt-f to format

**Expected behavior**
formatting according to formatter setting in vscode.

### Versions

deno: 0.22.0
v8: 7.9.317.12
typescript: 3.6.3

**Additional context**

Maybe it needs an option to control the formatting? Kinda like [prettier's](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) "semi" option?

**Comment by axetroy** [comment]
look at here https://github.com/denoland/deno/pull/3346.

next Deno version will support `.prettierrc.json` and `.prettierignore` in your project dir.

so, you can customize the prettier configuration

**Comment by axetroy** [comment]
deno@0.25.0 have been release. https://github.com/denoland/deno/releases/tag/v0.25.0

So I think it can be closed
