### ISSUE TITLE
Failed to detect Deno. in WSL

### ISSUE THREAD

**Issue by sunghwan2789** [justjavac/vscode-deno#58]
**Describe the bug**

vscode-deno fails to detect Deno in WSL(Windows Subsystem for Linux) environment.

**To Reproduce**

1. Install [Remote - WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) and Open Folder in WSL.
2. Install [vscode-deno](https://marketplace.visualstudio.com/items?itemName=justjavac.vscode-deno) and open .ts file.

**Screenshots**

![image](https://user-images.githubusercontent.com/4927894/69915801-85c2af80-1496-11ea-9a62-901a63b87e9d.png)

### Versions

* deno - `deno 0.25.0`
* vscode - `1.40.2 (user setup)`

**Additional context**

I use Ubuntu 18.04.3 LTS for WSL distro.

Maybe related to #1 .

**Comment by hsiaosiyuan0** [comment]
I'm afraid it not only occurs in WSL but also in all Platform since it's broken in my OSX, here is my versions:

- deno 0.26.0
- vscode 1.40.2

**Comment by justjavac** [comment]
new deno changes the `deno version` commond, I will fix it later

**Comment by marcuswhybrow** [comment]
I've create a [pull request][pr] which should fix the issue.

[pr]: https://github.com/justjavac/vscode-deno/pull/67

**Comment by marcuswhybrow** [comment]
Turns out the issue for me was my PATH. I had added deno to my PATH only in `~/.bashrc` whereas it was supposed to go in `~/.bash_profile`:

~~~~bash
export DENO_INSTALL="/home/marcus/.local"
export PATH="$DENO_INSTALL/bin:$PATH"
~~~~

No output errors now!
