### ISSUE TITLE
Prettier extension stops working when vscode-deno is activated

### ISSUE THREAD

**Issue by David-Else** [justjavac/vscode-deno#62]
**Describe the bug**

Activate Deno 1.4.0 deno extension and `esbenp.prettier-vscode` stops working. It should format on save, and instead it does nothing. Disable Deno extension and it works again.

I have not turned on `deno.autoFmtOnSave` or changed any vscode-deno settings.

### Versions

```
deno --version
deno 0.29.0
v8 8.1.108
typescript 3.7.2
```
```
Name: Prettier - Code formatter
Id: esbenp.prettier-vscode
Description: Code formatter using prettier
Version: 3.18.0
Publisher: Esben Petersen
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
```
```
Linux Centos 8
```

**Comment by brandonkal** [comment]
@justjavac any clue on why this is happening?

**Comment by clmay** [comment]
Same issue. Why would this extension try to format Markdown? It's not even a Markdown extension.

I'm not that familiar with packaging VS Code extensions, but I wonder if it's because of lines 122-125 in [`package.json`](https://github.com/justjavac/vscode-deno/blob/e8a3b47f47555403191a6463defc5736550fc6ad/package.json)?

```
...
"[markdown]":
  "editor.formatOnSave": false,
  "editor.defaultFormatter": "justjavac.vscode-deno"
}
...
```

In any case, for now I am using the following in my `settings.json` as a workaround and it solves the problem (again, for now; this should not even be required):

```
"[markdown]": {
  "editor.defaultFormatter": "esbenp.prettier-vscode"
},
```

**Comment by brandonkal** [comment]
That's it. This extension shouldn't contribute that especially since the deno formatter is not implemented.

**Comment by axetroy** [comment]
@clmay 

Hi. Because Deno supports formatting ts/js/markdown/json files.

In the future `"editor.formatOnSave": false,` and `deno.autoFmtOnSave`

Temporarily unable to determine if it conflicts with prettier

Maybe it will be resolved after #64 land

**Comment by brandonkal** [comment]
The deno binary can format other files because `deno fmt` is just a wrapper around Prettier. Ideally a deno formatter would be a seperate extension or a config for the existing prettier vscode extension.

**Comment by axetroy** [comment]
@brandonkal 
yeah. I know that.

I am one of maintainer of Deno. Prettier of Deno is also my job.

I just want to say that since it is a format, we need to support `Typescript/Javascript/Markdown/JSON`. Keep the consistency with `deno fmt`

Of course this is an option

If you have installed `vscode-prettier`

You can use `vscode-prettier` as a formatting tool in the configuration item of vscode.

```json
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
```

**Comment by brandonkal** [comment]
@axetroy My point here is that this extension should not be so intrusive. It is better to leave Prettier extension to handle all that it can handle. It should not be setting `"editor.formatOnSave": false` or overriding typescript language config. Not all TypeScript code is Deno code. It shouldn't even be an option of this extension. Calling out to deno to then run prettier will be slower as well. If users want that, it should be provided as part of a "vscode-deno-fmt" extension.

**Comment by David-Else** [comment]
@brandonkal I like the idea of ditching the Prettier extension and using deno exclusively if it can format **ALL** JS/TS/JSON and Markdown which I believe the re-write does https://github.com/justjavac/vscode-deno/pull/64. It would be one less extension to worry about, but I do agree it should be opt in otherwise it will confuse users who have the prettier extension installed.

>  Calling out to deno to then run prettier will be slower than invoking it directly.

I don't see why this should be a fact, deno has clever caching for compilation, maybe it does for formatting? Why would it be slower anyway? Maybe @axetroy could comment?

**Comment by dnl-brnr** [comment]
> It should not be setting `"editor.formatOnSave": false` or overriding typescript language config. Not all TypeScript code is Deno code. 

This is exactly right. The Deno extension is overstepping its boundary here and introducing a hard to track VS Code configuration bug. Any such settings should have to be explicitly set.

**Comment by brandonpsmith** [comment]
The only way I could get prettier to format on save with both extensions installed and enabled ...

```json
  "[javascript]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
```

**Comment by dnl-brnr** [comment]
@brandonpsmith  

This should work as well, and is _slightly_ drier. It makes sense if you use prettier for most of your formatting (HTML, CSS, markdown, YAML, etc.).

`settings.json`:

```jsonc
{
  // global
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,

  // override vscode-deno until it's fixed
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  }
}
```

**Comment by David-Else** [comment]
@dnl-brnr @brandonkal How about the new extension re-write? https://marketplace.visualstudio.com/items?itemName=axetroy.vscode-deno . It only just came out... I am going to have a look :)

**Comment by brandonpsmith** [comment]
> @brandonpsmith
> 
> This should work as well, and is _slightly_ drier. It makes sense if you use prettier for most of your formatting (HTML, CSS, markdown, YAML, etc.).
> 
> `settings.json`:
> 
> ```js
> {
>   // global
>   "editor.defaultFormatter": "esbenp.prettier-vscode",
>   "editor.formatOnSave": true,
> 
>   // override vscode-deno until it's fixed
>   "[typescript]": {
>     "editor.defaultFormatter": "esbenp.prettier-vscode",
>     "editor.formatOnSave": true
>   }
> }
> ```

yep. that works.

**Comment by David-Else** [comment]
This extension seems unmaintained now, switching to https://github.com/axetroy/vscode-deno and closing this issue.
