### ISSUE TITLE
top level await

### ISSUE THREAD

**Issue by brandonkal** [justjavac/vscode-deno#63]
Top level await is not allowed when Deno extension is enabled. Deno allows this, so no type errors should be shown.

**Comment by David-Else** [comment]
I assume that would be fixed with VS Code in the next version with TypeScript 3.8 built in which allows top level await. 

I tried it in the insiders and it is not working yet. It says the following even though my settings are correct and it should be allowed:
```
'await' outside of an async function is only allowed at the top level of a module when '--module' is 'esnext' or 'system' and '--target' is 'es2017' or higher.ts(1375)
```
Looks like they are working on it :)

**Comment by jiverson** [comment]
You can just add `// @ts-ignore` for the time being.

**Comment by magichim** [comment]
Could you make default feature?

**Comment by vaclavbenes** [comment]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#-top-level-await

**Comment by justjavac** [comment]
supported
