### ISSUE TITLE
VSCode type acquisition stops working when Deno extension is enabled

### ISSUE THREAD

**Issue by FOSSforlife** [justjavac/vscode-deno#70]
**Describe the bug**

When the Deno extension is enabled and I open a Jest file, VSCode will show the following [error](https://github.com/kulshekhar/ts-jest/issues/889): `Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try npm i @types/jest or npm i @types/mocha.. `

Even after running `npm i @types/jest` and ensuring that the package is there, VSCode is still unable to read it, and thus cannot find "describe", "it", "expect", or any other global Jest types. When I disable Deno, this works just fine.

**To Reproduce**

1. Make sure Deno VSCode extension is enabled. 
2. Clone any TypeScript repo that uses Jest, such as [microsoft/TypeScript-Node-Starter](https://github.com/microsoft/TypeScript-Node-Starter)
3. Open the repo in VSCode, run `npm i`
4. Open one of the files in the "test" folder, and after a few seconds there will be red squigglies under "describe", "it", and "expect". Mouse over and you'll get [this error](https://github.com/kulshekhar/ts-jest/issues/889).

**Expected behavior**

I expect that Jest files can be opened in VSCode without extraneous errors.

**Screenshots**

![Screenshot from 2020-03-07 17-51-39](https://user-images.githubusercontent.com/22383534/76155141-ea486880-609c-11ea-9eec-923f44328e6c.png)

### Versions

deno 0.35.0
v8 8.1.310
typescript 3.8.2
Deno Extension 1.4.0

**Additional context**

N/A.

**Comment by davelsan** [comment]
It also happens for common browser types, such as `HTMLElement`.

```ts
let el: HTMLElement;
```

> Cannot find name 'HTMLElement'

I understand it's possible this might be intended in a Deno project. I have to disable the extension in regular frontend / backend projects.

**Comment by birgersp** [comment]
Same goes for all my typescript projects (NodeJS). When the extension is enabled, VSCode will mark every single imported module as "not found". Took me quite a while to realize that the error occured after I started using this extension. 

Maybe it was an error on my end, but if nothing else then I think the README should mention that enabling the extension will give you problems with other (non-deno) types of VSCode projects.

**Comment by justjavac** [comment]
close via https://github.com/denoland/vscode_deno/pull/7
