### ISSUE TITLE
Cannot find module ts(2307) even when modules are cached locally

### ISSUE THREAD

**Issue by frankhale** [justjavac/vscode-deno#74]
Module import paths report that the module cannot be found even when the modules are cached locally. They have a red squiggly line under them.

**To Reproduce**

See screenshot below for very basic code example

**Expected behavior**

There should be no red squiggly line under my module paths. There shouldn't be an error being reported if I hover over them.

**Screenshots**

![image](https://user-images.githubusercontent.com/190154/79643974-d7cd4e80-8173-11ea-9875-3df6addfc80a.png)

### Versions

deno 0.41.0
v8 8.2.308
typescript 3.8.3

**Comment by justjavac** [comment]
I found the reason and plan to refactor the code next week.

**Comment by justjavac** [comment]
fixed
