### ISSUE TITLE
Error when formatting code

### ISSUE THREAD

**Issue by shaunxu** [justjavac/vscode-deno#75]
**Describe the bug**

After enabled Deno Extension when I formated my code in VSCode (press Cmd+Opt-L) I got an error message said

Command failed with exit code 1: deno run --allow-read https://deno.land/std/prettier/main.ts cat.ts
[0m[38;5;10mDownload[0m https://deno.land/std/prettier/main.ts
Import 'https://deno.land/std/prettier/main.ts' failed: 404 Not Found

<img width="570" alt="Screen Shot 2020-04-28 at 10 09 21" src="https://user-images.githubusercontent.com/554989/80439330-e0264600-8938-11ea-8cc7-841517814fcf.png">

**To Reproduce**

1. Install extension
2. Write some code (normal TS code regardless using Deno or not)
3. Format document (I was using Cmd+Opt+L)

**Expected behavior**

Code formatted.

### Versions

deno 0.41.0
v8 8.2.308
typescript 3.8.3

**Additional context**

I'm pointing my tsserver to the workspace folder but in my Deno application I didn't install typescript. VSCode said it fallback to the build-in tsserver.

**Comment by shaunxu** [comment]
Just a follow up message. I installed `typescript` and `typescript-deno-plugin` and configured them in my `tsconfig.json` the format command works well.

**Comment by shaunxu** [comment]
Just a follow up message. After uninstall the deno extension and install `typescript` and `typescript-deno-plugin` and configured them in `tsconfig.json` the format command works well.

**Comment by justjavac** [comment]
The formater of Deno has been changed, this will be rewrite in later versions

**Comment by joehillen** [comment]
axetroy.vscode-deno already supports the new formatter https://github.com/axetroy/vscode-deno/pull/50

**Comment by justjavac** [comment]
fixed via https://github.com/denoland/vscode_deno/pull/10
