### ISSUE TITLE
Failed to detect Deno on Ubuntu

### ISSUE THREAD

**Issue by Nugine** [justjavac/vscode-deno#77]
**Describe the bug**

Failed to detect Deno on Ubuntu.

**To Reproduce**

Just install `vscode-deno`.

**Expected behavior**

`vscode-deno` should be able to find the `deno` command.

**Screenshots**

![2020-05-08_20-19](https://user-images.githubusercontent.com/30099658/81404958-4bf28500-9169-11ea-8969-79bcaace448d.png)

![2020-05-08_20-18](https://user-images.githubusercontent.com/30099658/81405125-a25fc380-9169-11ea-8615-d94553bf2f2c.png)

### Versions

Deno

```
deno 1.0.0-rc1
v8 8.2.308
typescript 3.8.3
```

VSCode

```
版本: 1.45.0
提交: d69a79b73808559a91206d73d7717ff5f798f23c
日期: 2020-05-07T16:10:24.511Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-51-generic
```

**Additional context**

I guess that the problem is here: [src/deno.ts#L215](https://github.com/justjavac/vscode-deno/blob/8644c6d877b26b550134a0b227d50dc1b24c800d/src/deno.ts#L215)

**Comment by justjavac** [comment]
try to reload workspace

**Comment by Nugine** [comment]
I have rebooted. The problem still exists.

**Comment by justjavac** [comment]
fixed
